replicaCount: 1

image:
  repository: "spring-petclinic-config-server"
  tag: ""           # falls back to .Values.global.imageTag
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8888

resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 100m
