apiVersion: v1
kind: Secret
metadata:
  name: genai-secret
  namespace: {{ .Values.global.namespace | default "petclinic" }}
  labels:
    {{- include "genai-service.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.genaiSecret.openaiApiKey | b64enc | quote }}
  AZURE_OPENAI_KEY: {{ .Values.genaiSecret.azureOpenaiKey | b64enc | quote }}
  AZURE_OPENAI_ENDPOINT: {{ .Values.genaiSecret.azureOpenaiEndpoint | b64enc | quote }}
