apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: {{ .Values.global.namespace | default "petclinic" }}
  labels:
    {{- include "genai-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    {{- include "genai-service.selectorLabels" . | nindent 4 }}
