replicaCount: 1

image:
  repository: "spring-petclinic-prometheus"
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

resources:
  limits:
    memory: 256Mi
    cpu: 300m
  requests:
    memory: 128Mi
    cpu: 100m
