apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: {{ .Values.global.namespace | default "petclinic" }}
  labels:
    {{- include "discovery-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8761
      protocol: TCP
      name: http
  selector:
    {{- include "discovery-server.selectorLabels" . | nindent 4 }}
